cabal-version:      3.12
name:               grep
-- PVP summary:     +-+------- breaking API changes
--                  | | +----- non-breaking API additions
--                  | | | +--- code changes with no API change
version:            0.1.0.0

-- synopsis:
-- description:

license:            NONE
author:             Roan
maintainer:         none@email.com
build-type:         Simple

common warnings
    ghc-options: -Wall

executable grep
    import:           warnings
    main-is:          Main.hs
    other-modules:    Constants
                    , Parse
                    , Ansi
                    , Search
                    , Types
                    , Format

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:
    build-depends:    base ^>=4.17.2.1
                    , mtl ^>=2.2.2

    hs-source-dirs:   app
    default-language: Haskell2010
